/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteAmplication1Args } from "./DeleteAmplication1Args";
import { Amplication1FindManyArgs } from "./Amplication1FindManyArgs";
import { Amplication1FindUniqueArgs } from "./Amplication1FindUniqueArgs";
import { Amplication1 } from "./Amplication1";
import { Amplication1Service } from "../amplication1.service";

@graphql.Resolver(() => Amplication1)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class Amplication1ResolverBase {
  constructor(
    protected readonly service: Amplication1Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Amplication1",
    action: "read",
    possession: "any",
  })
  async _amplication1sMeta(
    @graphql.Args() args: Amplication1FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Amplication1])
  @nestAccessControl.UseRoles({
    resource: "Amplication1",
    action: "read",
    possession: "any",
  })
  async amplication1s(
    @graphql.Args() args: Amplication1FindManyArgs
  ): Promise<Amplication1[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Amplication1, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Amplication1",
    action: "read",
    possession: "own",
  })
  async amplication1(
    @graphql.Args() args: Amplication1FindUniqueArgs
  ): Promise<Amplication1 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Amplication1)
  @nestAccessControl.UseRoles({
    resource: "Amplication1",
    action: "delete",
    possession: "any",
  })
  async deleteAmplication1(
    @graphql.Args() args: DeleteAmplication1Args
  ): Promise<Amplication1 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
